os: linux
arch:
  - arm64
  - ppc64le
  - s390x
language: python
python:
  - "3.9"
# command to install dependencies
install:
  - pip install --upgrade pip
script:
  - python -c 'print("Travis working")'